### ISSUE TITLE
Analyses cause check-model-has-description failure

### ISSUE THREAD

**Issue by tim-steinkuhler** [Montreal-Analytics/dbt-gloss-deprecated#18]
**Describe the bug**
When I added an analysis file accompanied by a yaml file with a description, check-model-has-description still fails, saying it doesn't have a description.

This can be fixed by either excluding analyses from this check or correctly looking for analysis descriptions.

**To Reproduce**
1. Install codegen with `dbt deps`
2. Create a sql file in the analyses folder, and a yaml file with a description
3. run the check-model-has-description check

```yaml
# packages.yml
packages:
  - package: dbt-labs/codegen
    version: 0.8.1
```

```sql
--generate_model_yaml.sql
{{ codegen.generate_model_yaml(
    model_name='base_trengo_tickets_tickets_custom_data'
) }}

```

```yaml
# generate_model_yaml.yml
version: 2
analyses:
  - name: generate_model_yaml
    description: >
        This analyses generates the input necessary for a .yml file,
        by adding the model name without extensions and then hit compile.
        The output can then be copied and pasted into the designated yml file.

```

```yaml
# .pre-commit-config.yaml
 - repo: https://github.com/Montreal-Analytics/dbt-gloss
    rev: v1.0.0
    hooks:
      - id: dbt-deps
      - id: dbt-compile
      - id: dbt-run
      - id: dbt-docs-generate
      # Check the model has description.
      - id: check-model-has-description
```

<img width="1364" alt="afbeelding" src="https://user-images.githubusercontent.com/22643276/203821104-85f6b2f8-8e83-48ee-943c-19a39d31f94a.png">

**Expected behavior**
I expect check to pass

**Version:**
v1.0.0
